# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimmy Q
email: marioqsc2013@hotmail.com
description: This is my blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jimmyqsc.github.io" # the base hostname & protocol for your site
github_username:  JimmyQsc
bg-img: http://i.niupic.com/images/2016/08/10/gr1SMB.jpg
paginate: 5

# Build settings
markdown: kramdown

# Default settings
defaults:
  -
    scope:
      path: ""
      type: 'posts'
    values:
      author: Jimmy Q
      layout: 'post'
      comments: true

